# Generated by Django 3.2 on 2021-04-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='In process', max_length=10)),
                ('todo_priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todo.priority')),
            ],
        ),
    ]
