# Generated by Django 3.2 on 2021-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210410_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='In process', max_length=10),
        ),
    ]
